version: '3.8'

services:
  rss-monitor:
    # 使用GitHub构建的镜像，如果本地构建则注释掉image行，取消注释build行
    image: ghcr.io/yan-nian/rss-tv-monitor:latest
    # build: .
    container_name: rss-monitor
    ports:
      - "3000:80"    # 前端访问端口
      - "3001:3001"  # 后端API端口
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3001
      # 可选：配置环境变量
      # - TMDB_API_KEY=${TMDB_API_KEY}
      # - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    volumes:
      # 持久化存储应用数据
      - rss-data:/app/data
      # 可选：挂载本地配置文件
      # - ./config:/app/config
    networks:
      - rss-network
    labels:
      - "com.docker.compose.project=rss-monitor"
      - "description=RSS影视剧监控工具"
      - "version=latest"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  rss-network:
    driver: bridge
    labels:
      - "com.docker.compose.network=rss-monitor"

volumes:
  rss-data:
    driver: local
    labels:
      - "com.docker.compose.volume=rss-monitor-data"